name: CI
run-name: ${{ inputs.reason }}

on:
  push:
    paths:
      - .github/workflows/ci.yaml
      - src/**
      - website/**
      - '**/package.json'
      - pnpm-lock.yaml
  pull_request:
    paths:
      - .github/workflows/ci.yaml
      - src/**
      - website/**
      - '**/package.json'
      - pnpm-lock.yaml
  workflow_dispatch:
    inputs:
      reason:
        description: Dispatch reason
        type: string
        required: true

jobs:
  code-check:
    name: Run Code Check Workflow
    uses: ./.github/workflows/code-check.yaml
  code-tests:
    name: Run Tests Workflow
    uses: ./.github/workflows/code-test.yaml
