name: CI

on:
  push:
    paths:
      - .github/workflows/ci.yaml
      - src/**
      - .prettierrc
      - build.config.ts
      - package.json
      - pnpm-lock.yaml
      - tsconfig.json
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/ci.yaml
      - src/**
      - .prettierrc
      - build.config.ts
      - package.json
      - pnpm-lock.yaml
      - tsconfig.json

jobs:
  build_and_lint:
    name: Build and Lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: [18, 20, latest]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v3

      - name: Install Node ${{ matrix.node_version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node_version }}
          cache: pnpm

      - name: Install packages
        run: pnpm i

      - name: Check formatting
        run: pnpm lint:prettier

      - name: Build package
        run: pnpm build
