name: Run Tests

on:
  workflow_call:
    inputs:
      runs-on:
        description: Runs on
        default: ubuntu-latest
        type: string
      node-version:
        description: Node.js version
        default: latest
        type: string

jobs:
  run-tests:
    name: Run Tests
    runs-on: ${{ inputs.runs-on }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set-up pnpm
        uses: pnpm/action-setup@v4

      - name: Set-up Node.js ${{ inputs.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ inputs.node-version }}
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Run tests
        run: pnpm test
