name: Publish Documentation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_run:
    workflows: [CI, Release]
    types: [completed]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  publish:
    name: Publish Documentation
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'push' ||
        github.event_name == 'pull_request' ||
        (github.event_name == 'workflow_run' &&
          github.event.workflow_run.conclusion == 'success')
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up GitHub Pages
        uses: actions/configure-pages@v5

      - name: Set up pnpm
        uses: pnpm/action-setup@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: latest
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build documentation
        run: pnpm build:docs

      - name: Upload artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs

      - name: Deploy to GitHub Pages
        id: deploy
        uses: actions/deploy-pages@v4
        with:
          preview: ${{ github.event_name == 'push' || github.event_name == 'pull_request' }}
