name: Release Please

on:
  push:
    branches:
      - main

jobs:
  release-please:
    name: Run Release Please
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    outputs:
      release-created: ${{ steps.release-please.outputs.release_created }}
    steps:
      - name: Run Release Please Action
        id: release-please
        uses: googleapis/release-please-action@v4
        with:
          token: ${{ github.token }}
          config-file: .github/release-please-config.json
          manifest-file: .github/release-please-manifest.json
  publish-packages:
    name: Publish Packages
    runs-on: ubuntu-latest
    needs: release-please
    permissions:
      contents: read
      id-token: write
    if: needs.release-please.outputs.release-created == 'true'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set-up pnpm
        uses: pnpm/action-setup@v4

      - name: Set-up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: latest
          registry-url: https://registry.npmjs.org
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Publish to npm
        run: pnpm publish --access public --provenance
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
